CREATE TYPE attendance_status AS ENUM ('off_duty', 'on_duty', 'on_break');
CREATE TYPE attendance_action AS ENUM ('clock_in', 'clock_out');

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name TEXT NOT NULL CHECK (length(btrim(display_name)) BETWEEN 1 AND 120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE trusted_devices (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_fingerprint VARCHAR(64) NOT NULL
        CHECK (device_fingerprint ~ '^[0-9a-f]{64}$'),
    device_info JSONB NOT NULL CHECK (jsonb_typeof(device_info) = 'object'),
    trusted_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    UNIQUE (user_id, device_fingerprint)
);

CREATE INDEX trusted_devices_active_lookup_idx
    ON trusted_devices (user_id, device_fingerprint)
    WHERE revoked_at IS NULL;

CREATE TABLE attendance_states (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    state attendance_status NOT NULL DEFAULT 'off_duty',
    active_since TIMESTAMPTZ,
    last_action_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (
        (state = 'off_duty' AND active_since IS NULL)
        OR (state IN ('on_duty', 'on_break') AND active_since IS NOT NULL)
    )
);

CREATE TABLE attendance_records (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    action attendance_action NOT NULL,
    state_before attendance_status NOT NULL,
    state_after attendance_status NOT NULL,
    server_time TIMESTAMPTZ NOT NULL,
    client_time TIMESTAMPTZ NOT NULL,
    ip_address INET NOT NULL,
    device_fingerprint VARCHAR(64) NOT NULL
        CHECK (device_fingerprint ~ '^[0-9a-f]{64}$'),
    device_info JSONB NOT NULL CHECK (jsonb_typeof(device_info) = 'object'),
    work_duration INTERVAL,
    touch_duration_ms INTEGER NOT NULL CHECK (touch_duration_ms BETWEEN 50 AND 10000),
    touch_distance_px DOUBLE PRECISION NOT NULL CHECK (
        touch_distance_px >= 0
        AND touch_distance_px NOT IN ('NaN'::DOUBLE PRECISION, 'Infinity'::DOUBLE PRECISION)
    ),
    touch_sample_count INTEGER NOT NULL CHECK (touch_sample_count BETWEEN 1 AND 10000),
    request_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, request_id),
    CHECK (
        (action = 'clock_in' AND work_duration IS NULL)
        OR (action = 'clock_out' AND work_duration IS NOT NULL AND work_duration >= INTERVAL '0')
    )
);

CREATE INDEX attendance_records_user_time_idx
    ON attendance_records (user_id, server_time DESC);

CREATE INDEX attendance_records_completed_shift_idx
    ON attendance_records (user_id, server_time)
    WHERE action = 'clock_out';
